const mongoose = require("mongoose");

const userstatusSchema = new mongoose.Schema(
  {
    phoneNumber: String,
    uid: String,
    totalWorksheetsAttempted: { type: Number, default: 0 },
    totalWorksheetsCompleted: { type: Number, default: 0 },
    totalMathWorksheetsAttempted: { type: Number, default: 0 },
    totalMathWorksheetsCompleted: { type: Number, default: 0 },
    totalEnglishWorksheetsAttempted: { type: Number, default: 0 },
    totalEnglishWorksheetsCompleted: { type: Number, default: 0 },
    totalHindiWorksheetsAttempted: { type: Number, default: 0 },
    totalHindiWorksheetsCompleted: { type: Number, default: 0 },
    totalVideosStart: { type: Number, default: 0 },
    totalVideosCompleted: { type: Number, default: 0 },
    totalChildVidStart: { type: Number, default: 0 },
    totalChildVidCompleted: { type: Number, default: 0 },
    totalParentVidStart: { type: Number, default: 0 },
    totalParentVidCompleted: { type: Number, default: 0 },
    totalViewAndDoVidStart: { type: Number, default: 0 },
    totalViewAndDoVidCompleted: { type: Number, default: 0 },
    totalQuestionWSAttempted: { type: Number, default: 0 },
    totalQuestionWSCompleted: { type: Number, default: 0 },
    totalQuizQuestionCompleted: { type: Number, default: 0 },
    totalQuizQuestionAttempted: { type: Number, default: 0 },
    totalScoreMathMnth1: { type: Number, default: 0 },
    totalScoreEngMnth1: { type: Number, default: 0 },
    totalScoreHinMnth1: { type: Number, default: 0 },
    totalScoreMathMnth2: { type: Number, default: 0 },
    totalScoreEngMnth2: { type: Number, default: 0 },
    totalScoreHinMnth2: { type: Number, default: 0 },
    totalScoreMathMnth3: { type: Number, default: 0 },
    totalScoreEngMnth3: { type: Number, default: 0 },
    totalScoreHinMnth3: { type: Number, default: 0 },
    totalScoreMathMnth4: { type: Number, default: 0 },
    totalScoreEngMnth4: { type: Number, default: 0 },
    totalScoreHinMnth4: { type: Number, default: 0 },
    totalScoreMathMnth5: { type: Number, default: 0 },
    totalScoreEngMnth5: { type: Number, default: 0 },
    totalScoreHinMnth5: { type: Number, default: 0 },
    totalScoreMathMnth6: { type: Number, default: 0 },
    totalScoreEngMnth6: { type: Number, default: 0 },
    totalScoreHinMnth6: { type: Number, default: 0 },
    totalScoreMathMnth7: { type: Number, default: 0 },
    totalScoreEngMnth7: { type: Number, default: 0 },
    totalScoreHinMnth7: { type: Number, default: 0 },
    totalScoreMathMnth8: { type: Number, default: 0 },
    totalScoreEngMnth8: { type: Number, default: 0 },
    totalScoreHinMnth8: { type: Number, default: 0 },
    totalScoreMathMnth9: { type: Number, default: 0 },
    totalScoreEngMnth9: { type: Number, default: 0 },
    totalScoreHinMnth9: { type: Number, default: 0 },
    totalScoreMathMnth10: { type: Number, default: 0 },
    totalScoreEngMnth10: { type: Number, default: 0 },
    totalScoreHinMnth10: { type: Number, default: 0 },
    totalScoreMathMnth11: { type: Number, default: 0 },
    totalScoreEngMnth11: { type: Number, default: 0 },
    totalScoreHinMnth11: { type: Number, default: 0 },
    totalScoreMathMnth12: { type: Number, default: 0 },
    totalScoreEngMnth12: { type: Number, default: 0 },
    totalScoreHinMnth12: { type: Number, default: 0 },
  },

  {
    versionKey: false,
    timestamps: true,
  }
);

module.exports = mongoose.model("userstatus", userstatusSchema);
