const mongoose = require("mongoose");

const userstatusSchema = new mongoose.Schema(
  {
    name: String,
    picture: String,
    email: String,
    phoneNumber: String,
    address: String,
    state: String,
    city: String,
    zipCode: String,
    provider: String,
    accessToken: String,
    uid: String,
    gender: Number,
    adId: String,
    startDate: { type: Date },
    newTourCompleted: { type: Number, default: 0 },
    newChildAge: String,
    childGender: String,
    eulaTimestamp: Date,
    OnboardingComplete: { type: Boolean },
    childName: String,
    childSchoolType: String,
    childSchoolName: String,
    childSchoolCity: String,
    childSchoolState: String,
    partnerUser: Boolean,
    score: { type: Number },
    rank: { type: Number },
    leaderboardScore: { type: Number },
    currentWeek: { type: Number, default: 1 },
    uninstall: { type: Boolean, default: false },
    totalWorksheetsAttempted: { type: Number, default: 0 },
    totalWorksheetsCompleted: { type: Number, default: 0 },
    totalMathWorksheetsAttempted: { type: Number, default: 0 },
    totalMathWorksheetsCompleted: { type: Number, default: 0 },
    totalEnglishWorksheetsAttempted: { type: Number, default: 0 },
    totalEnglishWorksheetsCompleted: { type: Number, default: 0 },
    totalHindiWorksheetsAttempted: { type: Number, default: 0 },
    totalHindiWorksheetsCompleted: { type: Number, default: 0 },
    totalVideosStart: { type: Number, default: 0 },
    totalVideosCompleted: { type: Number, default: 0 },
    totalChildVidStart: { type: Number, default: 0 },
    totalChildVidCompleted: { type: Number, default: 0 },
    totalParentVidStart: { type: Number, default: 0 },
    totalParentVidCompleted: { type: Number, default: 0 },
    totalViewAndDoVidStart: { type: Number, default: 0 },
    totalViewAndDoVidCompleted: { type: Number, default: 0 },
  },

  {
    versionKey: false,
    timestamps: true,
  }
);

module.exports = mongoose.model("userstatus", userstatusSchema);
